### ISSUE TITLE
新添加 RJ284644 时没有显示购买日期

### ISSUE THREAD

**Issue by ShadowLyin** [Watanuki-Kimihiro/kikoeru-express#1]
本地系统: Windows 10 1909 专业版

软件版本: `0.2.0-win-x64` (使用 pm2 启动)

问题描述：
首先我首次扫描本地音声库并重启后，再次添加了 `RJ284644`，但是作品概览页没有显示日期（截图如下），而后我重新在添加了 `RJ284644` 时，却可以正常显示日期。
已尝试重启软件，但没有效果。

影响：使用按发售日从新到老排序时会默认排到最后。

截图：
![image](https://user-images.githubusercontent.com/20549332/79968335-864df800-84c2-11ea-870b-428d3f8ee945.png)

**Comment by yodhcn** [comment]
感谢你的反馈，我已经找到问题在哪里了。
你可以观察一下
https://www.dlsite.com/maniax/work/=/product_id/RJ284644.html
https://www.dlsite.com/maniax/work/=/product_id/RJ276074.html
这两个页面中 “贩卖日” 一项后面的信息格式不一样，导致没有办法抓到 RJ284644 的  “贩卖日” 数据，这个问题只要修改一下爬虫脚本应该能得到解决。

**Comment by ShadowLyin** [comment]
目前使用 v0.2.1 已解决问题，谢谢
