### ISSUE TITLE
iPad 无法播放 flac 格式的音频

### ISSUE THREAD

**Issue by ShadowLyin** [Watanuki-Kimihiro/kikoeru-express#11]
**本地环境：** 
iPad Air 3 
iPadOS 14.2
Safari/Chrome

**软件版本：** 
kikoeru-win-x64-v0.3.0，使用 PM2 启动

**问题描述：**
播放 flac 格式的音频文件时，播放器进度条不动，并且总时间一直显示 00:00（截图如下）。
播放其他类型的文件格式如 mp4/wav/mp3 可以正常播放，并且 flac 在 Windows 和 Android 上也可以正常播放。

**截图：**
<img width="352" alt="图片 2020-11-27 16-26-19" src="https://user-images.githubusercontent.com/20549332/100428195-966c2c80-30ce-11eb-8949-d20734cd91dc.png">

**Comment by shawncafu** [comment]
iOS好像都不行，我手里的mini/pro/iPhone都不行，之前13和现在14都一样

**Comment by umonaca** [comment]
我没有苹果设备，不方便测试，不过我的fork加了一个下载文件的功能，如果你能用其它软件打开通过浏览器下载的flac就可以自己用播放器离线播放了。

**Comment by ShadowLyin** [comment]
> 我没有苹果设备，不方便测试，不过我的fork加了一个下载文件的功能，如果你能用其它软件打开通过浏览器下载的flac就可以自己用播放器离线播放了。

我有在用了，谢谢，不过如果可以的话还是希望可以修复这个 bug

**Comment by umonaca** [comment]
在这个页面上能播放flac么？
https://hpr.dogphilosophy.net/test/

**Comment by ShadowLyin** [comment]
> 在这个页面上能播放flac么？
> https://hpr.dogphilosophy.net/test/

可以

**Comment by umonaca** [comment]
我觉得我知道该怎么修了。iOS不支持`audio/x-flac` MIME类型，但新系统支持`audio/flac`. 一会儿搞一下

**Comment by umonaca** [comment]
在我的v0.4.0修了
https://github.com/umonaca/kikoeru-express/releases/tag/v0.4.0

**Comment by ShadowLyin** [comment]
> 在我的v0.4.0修了
> https://github.com/umonaca/kikoeru-express/releases/tag/v0.4.0

好的，现在用的 v0.4.1 已经正常工作了
