### ISSUE TITLE
扫描音声库时某些作品显示「添加失败」

### ISSUE THREAD

**Issue by ShadowLyin** [Watanuki-Kimihiro/kikoeru-express#2]
### 本地环境：
Windows 10 专业版 1909

### 软件版本：
kikoeru-win-x64-v0.2.1，使用 PM2 启动

### 问题描述：
在扫描音声库时，有某些作品无法添加，显示添加失败（截图如下）
无法添加的作品有：RJ158326、RJ137139、RJ159645、RJ230560、RJ227084 等二十余部

### 截图：
![image](https://user-images.githubusercontent.com/20549332/80962852-66aebc00-8e40-11ea-8c5c-90abdb0162f4.png)

**Comment by cailuya** [comment]
v0.3.0已经修复了这个问题。

**Comment by ShadowLyin** [comment]
> v0.3.0已经修复了这个问题。

好的，目前已经没有问题了，谢谢。
