### ISSUE TITLE
所有新添加的作品的标题都会重复显示

### ISSUE THREAD

**Issue by ShadowLyin** [Watanuki-Kimihiro/kikoeru-express#7]
### 本地环境：
Windows 10 专业版 2004

### 软件版本：
kikoeru-win-x64-v0.3.0，使用 PM2 启动

### 问题描述：
所有新添加的作品的标题都会重复显示一次，导致所有的标题都显得很长．

### 截图：
![image](https://user-images.githubusercontent.com/20549332/96265107-9e2cb180-0ff7-11eb-8c33-dbebba603a60.png)

**Comment by equals-chan** [comment]
我也是...你不说我还没发现

**Comment by shawncafu** [comment]
我也是这个问题
环境是威联通的NAS

**Comment by shawncafu** [comment]
小白刚才百度下了一个能打开db.sqlite3的数据库，然后自己鼓捣了一下
用这个代码就能删除重复的标题了
update t_work set title=substr(title,1,(length(title)+3)/2)

**Comment by ShadowLyin** [comment]
> 小白刚才百度下了一个能打开db.sqlite3的数据库，然后自己鼓捣了一下
> 用这个代码就能删除重复的标题了
> update t_work set title=substr(title,1,(length(title)+3)/2)

感谢指引，使用了 SQLiteSpy 操作成功了。

**Comment by umonaca** [comment]
已经提交PR。是基于master的，和0.3.0有些区别，不过都是改这样一行。

**Comment by umonaca** [comment]
> 小白刚才百度下了一个能打开db.sqlite3的数据库，然后自己鼓捣了一下
> 用这个代码就能删除重复的标题了
> update t_work set title=substr(title,1,(length(title)+3)/2)

特别提醒，目前新增作品仍然会重复，并且这个SQL语句是对全体操作的。也就是说新增了以后临时解决方案是
```
update t_work set title=substr(title,1,(length(title)+3)/2) where id in (123456, 789012)
```
或者会node.js的话可以直接用我那个修复。不过，0.3.0要改的是54行而不是master的121行。

**Comment by ShadowLyin** [comment]
> > 小白刚才百度下了一个能打开db.sqlite3的数据库，然后自己鼓捣了一下
> > 用这个代码就能删除重复的标题了
> > update t_work set title=substr(title,1,(length(title)+3)/2)
> 
> 特别提醒，目前新增作品仍然会重复，并且这个SQL语句是对全体操作的。也就是说新增了以后临时解决方案是
> 
> ```
> update t_work set title=substr(title,1,(length(title)+3)/2) where id in (123456, 789012)
> ```
> 
> 或者会node.js的话可以直接用我那个修复。不过，0.3.0要改的是54行而不是master的121行。

目前改了这一行新添加的作品也正常了，感谢。

**Comment by equals-chan** [comment]
大家都是大佬....
我发现substr会对所有项进行修改，导致已经正常的标题字数被删减。
实际上我发现，重复的标题之间有一个换行符，并且标题会重复2-3次，所以我用java写了个小工具，利用`split("\n");`将重复标题分割成一个长度为2或3的String[] ，然后取一个即可。

**Comment by umonaca** [comment]
修复版程序：
https://github.com/umonaca/kikoeru-express/releases/tag/v0.3.1
直接解压，里面两个文件覆盖原版即可。基于0.3.0而非master，只改了这一处。

**Comment by shawncafu** [comment]
> 修复版程序：
> https://github.com/umonaca/kikoeru-express/releases/tag/v0.3.1
> 直接解压，里面两个文件覆盖原版即可。基于0.3.0而非master，只改了这一处。

大佬，我用的是docker版的，请问具体怎么操作修复呀

**Comment by umonaca** [comment]
> > 修复版程序：
> > https://github.com/umonaca/kikoeru-express/releases/tag/v0.3.1
> > 直接解压，里面两个文件覆盖原版即可。基于0.3.0而非master，只改了这一处。
> 
> 大佬，我用的是docker版的，请问具体怎么操作修复呀

先把相应的容器停掉，下载[这个文件](https://raw.githubusercontent.com/umonaca/kikoeru-express/stable/docker-compose.yml)，修改volume下冒号左侧为你的存储位置，然后docker-compose up
或者
```
docker run --init -p 8888:8888 -v 你的存储:/usr/src/kikoeru/Folder/VoiceWork -v 你的数据库:/usr/src/kikoeru/sqlite -v 你的封面:/usr/src/kikoeru/covers -v 你的设置:/usr/src/kikoeru/config muveexu/kikoeru:v0.3.4
```

==== 更新 ====
打包了docker image，放在release里面了。
